#!/usr/bin/env node
/**
 * Arc Platform — seed the local wp-env WooCommerce instance for contract tests.
 *
 * Prerequisites:
 *   - Docker Desktop running
 *   - `pnpm wp:start` (boots WordPress + WooCommerce + WPGraphQL + WooGraphQL)
 *
 * What it does:
 *   1. Sets pretty permalinks (required by the Store API AND WPGraphQL).
 *   2. Runs Scripts/wp-seed/seed.php inside the container via wp-cli.
 *   3. Writes .env.wp-test (gitignored) with every var the contract suite reads.
 *
 * Then run:  pnpm test:contract
 */

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const WP_URL = process.env.WP_URL ?? 'http://localhost:8888';
const WP_GRAPHQL_ENDPOINT = process.env.WP_GRAPHQL_ENDPOINT ?? `${WP_URL}/graphql`;

// Resolve wp-env's JS entry so we can run it via `node` directly. Spawning the
// `.cmd`/`.bin` shim with shell:false throws EINVAL on Windows (post-CVE Node),
// and shell:true would let cmd.exe expand `%postname%`-style args.
const wpEnvBin = path.join(
  path.dirname(require.resolve('@wordpress/env/package.json')),
  'bin',
  'wp-env',
);

/** Run a wp-cli command inside the wp-env `cli` container. */
function wp(args) {
  const res = spawnSync(process.execPath, [wpEnvBin, 'run', 'cli', 'wp', ...args], {
    encoding: 'utf8',
  });
  if (res.error) {
    throw res.error;
  }
  if (res.status !== 0) {
    process.stderr.write(res.stdout ?? '');
    process.stderr.write(res.stderr ?? '');
    throw new Error(`wp ${args.join(' ')} exited with ${res.status}`);
  }
  return res.stdout ?? '';
}

// Pretty permalinks via wp-cli (registers rewrite tags). A hard flush AFTER
// plugins/products exist is what actually exposes WPGraphQL's /graphql route —
// flush_rewrite_rules() inside `wp eval-file` does not. Safe to pass `%` here:
// we spawn `node` directly (no shell), so cmd.exe never expands `%postname%`.
console.log('→ Setting pretty permalinks…');
wp(['rewrite', 'structure', '/%postname%/', '--hard']);

console.log('→ Seeding WooCommerce fixtures…');
const out = wp(['eval-file', 'wp-content/arc-seed/seed.php']);
process.stdout.write(out);

console.log('→ Flushing rewrite rules (exposes /graphql)…');
wp(['rewrite', 'flush', '--hard']);

const match = out.match(/ARC_SEED_RESULT=(\{.*\})/);
if (!match) {
  throw new Error('Seeder did not emit ARC_SEED_RESULT — check the output above.');
}
const seed = JSON.parse(match[1]);

const lines = [
  '# Generated by Scripts/seed-wp-env.mjs — do not edit by hand. Gitignored.',
  'CI_WP_ENV=true',
  `WP_URL=${WP_URL}`,
  `ARC_WC_URL=${WP_URL}`,
  `WP_GRAPHQL_ENDPOINT=${WP_GRAPHQL_ENDPOINT}`,
  `TEST_PRODUCT_ID=${seed.product_id}`,
  `TEST_PRODUCT_SLUG=${seed.product_slug}`,
  `TEST_VARIABLE_PRODUCT_SLUG=${seed.variable_product_slug}`,
  `TEST_COUPON_CODE=${seed.coupon_code}`,
  `TEST_COLLECTION_SLUG=${seed.collection_slug}`,
  `TEST_ORDER_ID=${seed.order_id}`,
  // TEST_JWT_TOKEN is intentionally unset — authenticated customer GraphQL tests
  // skip without it (requires a JWT auth plugin; see customer-auth spike).
  '',
];
writeFileSync('.env.wp-test', lines.join('\n'));

console.log('\n✓ Seed complete. Wrote .env.wp-test');
console.log(`   TEST_PRODUCT_ID=${seed.product_id} (slug ${seed.product_slug})`);
console.log(`   TEST_VARIABLE_PRODUCT_SLUG=${seed.variable_product_slug}`);
console.log(`   TEST_COUPON_CODE=${seed.coupon_code}`);
console.log(`   TEST_COLLECTION_SLUG=${seed.collection_slug}`);
console.log(`   TEST_ORDER_ID=${seed.order_id}`);
console.log('\nNext:  pnpm test:contract');
